name: npflan-release

on:
  release:
    types: [released]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Build runtime
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: npflan/csgo-network-log-parser:latest, npflan/csgo-network-log-parser:${{ github.event.release.tag_name }}
          target: runtime